name: autoscheduler_assignment
description: A Flutter project for employee auto-scheduling with Firebase and Google Maps.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  http: ^1.2.2
  flutter_riverpod: ^2.5.1
  csv: ^6.0.0
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
